package:
  name: mutect
  version: "1.1.4"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/mutect.git

build:
  number: 3

requirements:
  run:
    - java-jdk 7.*

about:
  home: https://github.com/jason-weirather/mutect
  license: Custom
  license_file: mutect.LICENSE.TXT
